  checkpoint:
   save:  
    path: null
    # path: /storage_nvme_3/crewtool/nano_checkpoints/llama31_pc # entropy_c
    # path: /storage_nvme_3/mstefaniak/nano_checkpoints/llama31_pc # entropy
    # path: /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/pc # helios
   load:
    type: huggingface
    path: "meta-llama/Llama-3.2-1B"