# MASs checkpoints dependent on user slurm account - private fiels

trainer:
  checkpoint:
   save:
    interval: -1
    path: null
    model_checkpoint_filename: null
    training_state_filename: null

   load:
    type: huggingface
    path: "/home/mstefaniak/checkpoints/llama_1b" # entropy # TODO move to shared
    # path: "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/llama_1b" # helios # TODO move to shared
    model_checkpoint_filename: null