# MASs checkpoints dependent on user slurm account - private files

trainer:
  checkpoint:
   save:
    type: huggingface
    interval: -1
    path: ???
    model_checkpoint_filename: __model_checkpoint_filename.pt
    training_state_filename: __training_state_filename.pt

   load:
    type: nano
    path: ???
    model_checkpoint_filename: __model_checkpoint_filename.pt
    training_state_filename: null
    only_weights: true 
