defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    num_workers: 8
    dataset:
      data_generator:
        path: ${cluster_switch.train_path_c4}
  eval_dataloader:
    num_workers: 8
    dataset:
      seed: 22
      data_generator:
        path: ${cluster_switch.eval_path_c4}
