defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    dataset:
      data_generator:
        path: ${cluster_switch.train_path_fineweb}
  eval_dataloader:
    dataset:
      seed: 22
      data_generator:
        path: ${cluster_switch.eval_path_fineweb}
