defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    dataset:
      data_generator:
        path: ${cluster_switch.train_path_fineweb}
  eval_dataloader:
    dataset:
      seed: ${eval:'${common.data_seed} + 1000000'}
      data_generator:
        path: ${cluster_switch.eval_path_fineweb}
