defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    _target_: src.core.datasets.get_mixture_of_datasets_dataloader
    datasets:
      - path: ${cluster_switch.train_path_smollm_fineweb_edu}
        weight: 0.7
      - path: ${cluster_switch.train_path_smollm_cosmopedia}
        weight: 0.15
      - path: ${cluster_switch.train_path_smollm_python_edu}
        weight: 0.08
      - path: ${cluster_switch.train_path_smollm_open_web_math}
        weight: 0.07
    dataset_split: train
    num_workers: 2
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B

  eval_dataloader:
    _target_: src.core.datasets.get_mixture_of_datasets_dataloader
    datasets:
      - path: ${cluster_switch.train_path_smollm_fineweb_edu}
        weight: 0.7
      - path: ${cluster_switch.train_path_smollm_cosmopedia}
        weight: 0.15
      - path: ${cluster_switch.train_path_smollm_python_edu}
        weight: 0.08
      - path: ${cluster_switch.train_path_smollm_open_web_math}
        weight: 0.07
    dataset_split: validation
    num_workers: 1
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B
