trainer:
  checkpoint:
   save:
    interval: -1
    path: null
    model_checkpoint_filename: __model_checkpoint_filename.pt
    training_state_filename: __training_state_filename.pt

   load:
    type: null
    path: null
    model_checkpoint_filename: __model_checkpoint_filename.pt
    training_state_filename: __training_state_filename.pt