# @package _global_
defaults:
  - /_cluster/helios@_here_
  - /_model/tiny@_here_
  - /product_keys/pk_model@_here_
  - /_trainer/llama@_here_
  - /_dataset/sst2@_here_
  - /_checkpoints/none@_here_
  - /_misc/default@_here_
  - _self_


trainer:
  _target_: src.product_keys.finetuning_trainer.FinetuningTrainer
  gradient_accumulation_steps: 2
  n_steps: 20000
  learning_rate: 1e-3
  d_model: ${common.dmodel}
  vocab_size: ${common.vocab_size}

  checkpoint:
    load:
      type: nano
      path: /net/storage/pr3/plgrid/plggllmeffi3/pk_attention/model_checkpoints/plgggwozdz02/16187802/0/step_104
      model_checkpoint_filename: model_checkpoint.pt
      training_state_filename: training_state.pt
      only_weights: false 


infrastructure:
  metric_logger:
    type: wandb
    wandb_entity: ideas_cv
    project_name: tml-bgw
    name: TML_BGW-finetunetrainer-${now:%Y-%m-%d_%H-%M-%S}
    tags:
      - nano
      - pk_mlm
      - "seq_len=${common.sequence_length}"
      - "n_layers=${common.n_blocks}"
  slurm:
    gres: gpu:1
    time: "1-00:00:00"
    job-name: ${infrastructure.metric_logger.name}

