# @package _global_
defaults:
  - /_cluster/local@_here_
  - /_model/tiny@_here_
  - /_trainer/llama@_here_
  - /_dataset/sst2@_here_
  - /_checkpoints/none@_here_
  - /_misc/default@_here_
  - _self_

common:
  sequence_length: 16
  batch_size: 4
  dmodel: 16
  dff: 64
  datt: ${common.dmodel}
  n_blocks: 4
  q_heads: 2
  kv_heads: 2
  vocab_size: 128256


trainer:
  _target_: src.product_keys.finetuning_trainer.FinetuningTrainer
  gradient_accumulation_steps: 2
  n_steps: 2
  learning_rate: 1e-3

  train_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.product_keys.datasets.glue_tokenize_fn
        seq_len: ${common.sequence_length}

  eval_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.product_keys.datasets.glue_tokenize_fn
        seq_len: ${common.sequence_length}

  checkpoint:
    load:
      type: huggingface
      path: checkpoint
      model_checkpoint_filename: model.safetensors
    save:
      type: nano
      path: finetuned_checkpoint


infrastructure:
  metric_logger:
    type: stdout

model:
  encoder:
    block_fn:
      attention_fn:
        _target_: src.product_keys.model.RoPETopKAttention
        _partial_: true
        dmodel: ${common.dmodel}
        q_heads: ${common.q_heads}
        kv_heads: ${common.kv_heads}
        seq_len: ${common.sequence_length}

        q_proj_fn:
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

        k_proj_fn:
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.dmodel}
          out_features: ${eval:'(${common.datt} // ${model.encoder.block_fn.attention_fn.q_heads}) * ${model.encoder.block_fn.attention_fn.kv_heads}'}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

        v_proj_fn: ${model.encoder.block_fn.attention_fn.k_proj_fn}

        o_proj_fn: 
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.datt}
          out_features: ${common.dmodel}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

        rope_base: 500000
        rope_scale_freqs: true
        top_k: 16
        top_k_before_softmax: true
