# @package _global_
defaults:
  - /_cluster/helios@_here_
  - /_model/tiny@_here_
  - /product_keys/pk_model@_here_
  - /_trainer/llama@_here_
  - /_dataset/c4@_here_
  - /_misc/default@_here_
  - _self_


trainer:
  _target_: src.product_keys.trainer.MaskedLMTrainer
  masking_percentage: 0.2
  mask_token_id: 50257
  unmaskable_special_tokens: [50256, 50257]  # <|endoftext|>
  gradient_accumulation_steps: 4
  # n_steps: 77050
  n_steps: 10
  # ^learning_rate: [1e-4, 2e-4, 5e-4, 1e-3, 2e-3, 5e-3]
  learning_rate: 2e-3
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.get_cosine_scheduler_with_warmup
    final_lr_fraction: 0.1
    warmup_steps: ${eval:'int(${trainer.n_steps} * 0.10)'}
  train_dataloader:
    dataset:
      seed: 42
      tokenize_fn:
        _target_: src.product_keys.datasets.gpt2_mask_tokenize_fn
  eval_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.product_keys.datasets.gpt2_mask_tokenize_fn
  checkpoint:
    save:
      interval: -1
    # load:
    #   path: /net/storage/pr3/plgrid/plggllmeffi3/pk_attention/model_checkpoints/plgggwozdz02/16187802/0/step_104
    #   only_weights: false # false not tested


infrastructure:
  metric_logger:
    type: wandb
    wandb_entity: ideas_cv
    name: pk_mlm_${now:%Y-%m-%d_%H-%M-%S}
    project_name: tml-bgw
    heavy_metrics_calculation_interval: 1000
    heavy_logging_layers: [0, 10, 15]
    tags:
      - nano
      - pk_mlm
      - 2026.04.20
      - warmup_steps=${trainer.scheduler.warmup_steps}
      - RoPE
      # - learning_rate_grid
      # - "lr=${trainer.learning_rate}"
      - "seq_len=${common.sequence_length}"
      - "n_layers=${common.n_blocks}"
      - "dmodel=${common.dmodel}"
      - seed=${trainer.train_dataloader.dataset.seed}
  slurm:
    gres: gpu:2
    time: "1-00:00:00"
    job-name: ${infrastructure.metric_logger.name}


