_target_: src.core.moe.MoE
_partial_: true
dmodel: ${common.dmodel}
dff: ${common.dff}
num_experts: ???
topk: ???
capacity_factor: ???
moe_load_balancing_loss_factor: ???
moe_router_z_loss_factor: ???
normalize_router_logits: ???
activation_function: ???
init_scale: ???
