
common:
  _target_: src.definitions.Common
  dmodel: 1536
  dff: 6144
  datt: 1536
  n_blocks: 24
  q_heads: 24
  kv_heads: 24
  vocab_size: 50257
  sequence_length: 512
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  model_type: gpt
  
model:
  _target_: src.projected_compression.model.LLM

  embedding:
    _target_: src.projected_compression.model.TransformerEmbedding
    vocab_size: ${common.vocab_size}
    dmodel: ${common.dmodel}
    init_fn:
      _target_: src.projected_compression.model.llm_random_weight_init
      _partial_: true
      scale: 1

  encoder:
    _target_: src.projected_compression.model.TransformerEncoder
    n_blocks: ${common.n_blocks}
    block_fn:
      _target_: src.projected_compression.model.TransformerBlock
      _partial_: true
      norm_fn:
        _target_: src.core.model.LayerNorm
        _partial_: true
        eps: 1e-5
        normalized_shape: ${common.dmodel}
        bias: false

      attention_fn:
        _target_: src.projected_compression.model.RoPEAttention
        _partial_: true
        dmodel: ${common.dmodel}
        q_heads: ${common.q_heads}
        kv_heads: ${common.kv_heads}
        seq_len: ${common.sequence_length}
        q_proj_fn:
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

        k_proj_fn:
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

        v_proj_fn: ${model.encoder.block_fn.attention_fn.k_proj_fn}

        o_proj_fn: 
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.datt}
          out_features: ${common.dmodel}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

        rope_base: 10000
        rope_scale_freqs: false

      ff_layer_fn:
        _target_: src.projected_compression.model.FeedForward
        _partial_: true
        ff_pre_act_fn:
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.dmodel}
          out_features: ${common.dff}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1
        ff_post_act_fn:
          _target_: src.projected_compression.model.Linear
          _partial_: true
          in_features: ${common.dff}
          out_features: ${common.dmodel}
          partial_init_fn:
            _target_: src.projected_compression.model.llm_random_weight_init
            _partial_: true
            scale: 1

  head:
    _target_: src.projected_compression.model.TransformerHead
    linear_fn:
      _target_: src.projected_compression.model.Linear
      _partial_: true
      in_features: ${common.dmodel}
      out_features: ${common.vocab_size}
      partial_init_fn:
        _target_: src.projected_compression.model.llm_random_weight_init
        _partial_: true
        scale: 1
    norm_fn:
      _target_: src.core.model.LayerNorm
      _partial_: true
      eps: 1e-5
      normalized_shape: ${common.dmodel}
      bias: false