# @package _global_
defaults:
  - /_cluster@_here_:                lem
  - /_model/context_scaling@_here_:  template
  - /_trainer@_here_:                context_scaling
  - /_dataset@_here_:                fineweb
  - /_checkpoints/context_scaling@_here_: lem_1
  - /_infrastructure@_here_:         default
  # - /_downstream_eval@_here_:        joint

  - /_feedforward:                   moe
  - /_attention:                     mha
  - /_parameterization:              simpleP_k12
  - _self_

common:
  n_blocks: 12
  ^batch_size: [8, 16, 32, 64]
  sequence_length: 1024
  data_seed: 301  # eval seed is 22, so never use it as train seed

trainer:
  n_steps: 16_001
  ^learning_rate: [7, 8, 9, 10, 11, 12]
  eval_interval: 100  # remove for longer runs

# downstream_evaluator:
#   eval_interval: 0
#   final_eval: false

infrastructure:
  metric_logger:
    heavy_metrics_calculation_interval: 500 # change on longer runs
    name: critical_batch_size
    tags:
      - nano
      - critical_batch_size
      - moe
      - mha
      - simpleP_k12
      - k12
      - ${now:%Y-%m-%d}

  slurm:
    time: "0-04:00:00"
    gres: gpu:hopper:4
    job-name: ${infrastructure.metric_logger.name}
