# @package _global_
model:
  encoder:
    block_fn:
      ff_layer_fn:
        _target_: src.core.moe.MoE
        _partial_: true
        dmodel: ${common.dmodel}
        dff: ${common.dff}
        num_experts: 8
        topk: 1
        capacity_factor: 1.25
        moe_load_balancing_loss_factor: 0.01
        moe_router_z_loss_factor: 0.001
        normalize_router_logits: false
        activation_function: swiglu
        init_scale: ${common.init_scale}
