defaults:
  - ../../_cluster@_here_: entropy
  - ../../_model/smollm@_here_: projected_1700
  - ../../_trainer@_here_: llama
  - ../../_dataset@_here_: fineweb
  - ../../_checkpoints@_here_: none
  - ../../_misc@_here_: default

common:
  sequence_length: 1024
  batch_size: 512
  dmodel: 1344
  dff: 5376

trainer:
  gradient_accumulation_steps: 8
  ^n_steps:
    - 2048 # 1B tokens

  ^learning_rate:
    - 11
    - 12
    - 13
    - 14

  scheduler:
    warmup_steps: 40

  checkpoint:
    load:
      type: huggingface
      path: "HuggingFaceTB/SmolLM-1.7B"
    save:
      type: nano
      path: ??? # CHANGE
      interval: 2047
      model_checkpoint_filename: __model_checkpoint_filename.pt
      training_state_filename: __training_state_filename.pt

  train_dataloader:
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B

  eval_dataloader:
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B

infrastructure:
  metric_logger:
    name: SLLM_1700_comp_50_lr_grid
    tags:
      - nano
      - pc
      - smollm_1700
      - projected_compression
      - no_distillation
      - 50p
      - 1B_tokens
      - lr_grid

  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    time: "0-24:00:00"

apply_functions:
  - _target_: src.projected_compression.compression.init_compression
    _partial_: true
    dimensions_importances_path: ??? # CHANGE
    target_dmodel: ${common.dmodel}
    target_dff: ${common.dff}


