defaults:
  - ../../_cluster@_here_: entropy
  - ../../_model/smollm@_here_: def_1700
  - ../../_trainer@_here_: smollm_1700_distillation
  - ../../_dataset@_here_: smollm_corpus
  - ../../_checkpoints@_here_: none
  - ../../_misc@_here_: default
  - _self_

common:
  sequence_length: 1024
  batch_size: 512
  target_dmodel: 448
  target_dff: 1728

trainer:
  gradient_accumulation_steps: 8
  ^n_steps:
    # - 2048 # 1B tokens
    - 4096 # 2B tokens
    # - 8192 # 4B tokens
    # - 12288 # 6B tokens

  ^learning_rate:
    - 10
    # - 11
    # - 12
    # - 13
    # - 14

  scheduler:
    warmup_steps: 40

  original_llama_path: HuggingFaceTB/SmolLM-1.7B

  checkpoint:
    load:
      type: huggingface
      path: "HuggingFaceTB/SmolLM-1.7B"
    save:
      type: hf_only
      path: /storage_nvme_3/mstefaniak/pc/checkpoints
      interval: 0
      model_checkpoint_filename: __model_checkpoint_filename.pt
      training_state_filename: __training_state_filename.pt

  eval_interval: 1000000
  eval_dataloader: None
  train_dataloader:
    seed: 1000
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B

infrastructure:
  metric_logger:
    name: SLLM_1700_prune_distill_90_lr_grid
    tags:
      - nano
      - pc
      - smollm_1700
      - hard_pruning
      - distillation
      - 90p
      - 2B_tokens
      - lr_grid
      - mas
  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    time: "0-24:00:00"

apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    dimensions_importances_path: /storage_nvme_3/mstefaniak/pc/importances_smoll/177095/0/minitron_dimensions_importances.pt #entropy
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}
