defaults:
  - ../../_cluster@_here_: lem
  - ../../_model/qwen@_here_: projected_mem_eff_1.7B
  - ../../_trainer@_here_: qwen_1.7B_distillation
  - ../../_dataset@_here_: fineweb
  - ../../_checkpoints@_here_: none
  - ../../_misc@_here_: default

common:
  sequence_length: 1024
  batch_size: 512

  # base: dmodel 2048, dff 6144
  ^dmodel: [448, 960, 1344]
  dff: "${eval:'${common.dmodel} * 3'}"


trainer:
  _target_: src.projected_compression.trainer_distillation.PCDistillationTrainer
  gradient_accumulation_steps: 8
  ^n_steps:
    - 2048 # 1B tokens  <5h
    # - 4096 # 2B tokens    <10h
    # - 8192 # 4B tokens    <20h
    # # - 12288 # 6B tokens   <20h
    # - 16384 # 8B tokens   <40h

  gradient_clipping: 0.25 #best
  only_compress_model_gradient_clipping: false
  only_target_model_gradient_clipping: 1.0 #best

  learning_rate: 14

  scheduler:
    warmup_steps: 40

  distributed:
    fsdp2: null

  original_llama_path: Qwen/Qwen3-1.7B-Base # reference HF model for the qwen exporter

  eval_interval: 0 # PC_memeff does not work in eval inference mode
  eval_dataloader: None

  checkpoint: # only way to save PC_memeff model
    save:
      interval: 0  # 0 = only save at the end of training
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/checkpoints/pc_distil/qwen/1_7B # CHANGE
      training_state_filename: __training_state_filename.pt
      type: hf_only

projected_compression:
  modules_to_shard:
    - src.projected_compression.mem_eff.CompressibleBlock
    - ${model.source_model.embedding._target_}
    - ${model.source_model.encoder.block_fn._target_}
    - ${model.source_model.head._target_}

  source_model_path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/qwen3_1_7b_in_nano.pt # special PC_memeff checkpoint from newq_conversion config experiment
  path_to_importances: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/importances/qwen/1_7B/5403539/0/minitron_dimensions_importances.pt # CHANGE

  init_norms_with_ones: false

  separate_block_optimizers: true

  pc_weights_lr_ratio: 1.0 # lr multiplier for projection matrices (not aux weights)

  adjust_grad_norm: false

  cpu_offload_projections: false

  source_model_for_distillation: true

distillation:
  load:
    type: pc_memeff_base # uses internal teacher model representation for distillation to save memory - source_model_for_distillation: true

model:
  cast_bfloat16: true # whether to cast bfloat16 when calculating compressed matrix

infrastructure:
  metric_logger:
    name: Queen_PC
    tags:
      - nano
      - pc
      - qwen
      - 1.7B
      - projected_compression
      - distillation
      - "${eval:'{2048:\"1B_train\",4096:\"2B_train\",8192:\"4B_train\",16384:\"8B_train\"}[${trainer.n_steps}]'}"
      - mem_eff
      - "${eval:'{448:\"10p\",960:\"30p\",1344:\"50p\"}[${common.dmodel}]'}"

  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:hopper:4
    time: "2-12:00:00"
