defaults:
  - ../../_cluster@_here_: lem
  - ../../_model/qwen@_here_: 1.7B
  - ../../_trainer@_here_: qwen_1.7B_distillation
  - ../../_dataset@_here_: fineweb
  - ../../_checkpoints@_here_: none
  - ../../_misc@_here_: default


common:
  sequence_length: 1024
  batch_size: 512

  # base: dmodel 2048, dff 6144
  # target_dmodel: 1344 # 50
  # target_dff: 4032
  # target_dmodel: 960 # 30
  # target_dff: 2880
  ^target_dmodel: [448, 960, 1344]
  target_dff: "${eval:'${common.target_dmodel} * 3'}"


trainer:
  gradient_accumulation_steps: 8
  ^n_steps:
    # - 2048 # 1B tokens  <4.5h
    - 4096 # 2B tokens    <9h
    - 8192 # 4B tokens    <18h
    - 16384 # 8B tokens   <36h

  learning_rate: 11

  scheduler:
    warmup_steps: 40

  original_llama_path: Qwen/Qwen3-1.7B-Base # reference HF model for the qwen exporter

  checkpoint:
    load:
      type: huggingface_qwen
      path: "Qwen/Qwen3-1.7B-Base"
    save:
      type: hf_only
      path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/checkpoints/hp_distil/qwen/1_7B # CHANGE

  eval_interval: 0
  eval_dataloader: None
  train_dataloader:
    dataset:
      seed: 1000


infrastructure:
  metric_logger:
    name: Queen_HP
    tags:
      - nano
      - pc
      - qwen
      - 1.7B
      - hard_pruning
      - distillation
      - "${eval:'{2048:\"1B_train\",4096:\"2B_train\",8192:\"4B_train\",16384:\"8B_train\"}[${trainer.n_steps}]'}"
      - "${eval:'{448:\"10p\",960:\"30p\",1344:\"50p\"}[${common.target_dmodel}]'}"

  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:hopper:4
    time: "2-00:00:00"


apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    dimensions_importances_path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/importances/qwen/1_7B/5403539/0/minitron_dimensions_importances.pt # CHANGE
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}
