defaults:
  - ../_cluster@_here_: entropy
  - ../_model/context_scaling@_here_: k16
  - ../_trainer@_here_: context_scaling
  - ../_dataset@_here_: ctx_scl_dataset
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default
  - _self_

common:
  sequence_length: 2048
  batch_size: 8

trainer:
  gradient_accumulation_steps: 1
  n_steps: 40001
  # n_steps: 20001
  # n_steps: 10001
  # n_steps: 5001
  # n_steps: 2501
  ^learning_rate: [4, 6, 8, 10, 12]
  eval_interval: 500

simpleP:
  base_model:
    dmodel: 256
    dff: 640

infrastructure:
  metric_logger:
    name: simpleP_k16
    tags:
      - nano
      - simpleP_bsgrid
      - k16

  slurm:
    time: "0-03:00:00"
    gres: gpu:4
    job-name: ${infrastructure.metric_logger.name}
