defaults:
  - ../_cluster@_here_: entropy
  - ../_model/context_scaling@_here_: k20
  - ../_trainer@_here_: context_scaling
  - ../_dataset@_here_: ctx_scl_dataset
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default
  - _self_

common:
  sequence_length: 1024
  batch_size: 64

trainer:
  gradient_accumulation_steps: 1
  n_steps: 5001
  # ^learning_rate: [5]
  ^learning_rate: [5, 7, 9, 11, 13]
  eval_interval: 500

simpleP:
  base_model:
    dmodel: 256
    dff: 640

infrastructure:
  metric_logger:
    name: simpleP3_k20
    tags:
      - nano
      - simpleP3
      - k20

  slurm:
    time: "0-04:00:00"
    gres: gpu:4
    job-name: ${infrastructure.metric_logger.name}
