defaults:
  - ../_cluster@_here_: local
  - ../_model@_here_: tiny
  - ../_trainer@_here_: context_scaling
  - ../_dataset@_here_: ctx_scl_dataset
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default
  - _self_

common:
  sequence_length: 16
  batch_size: 2

trainer:
  gradient_accumulation_steps: 1
  n_steps: 21
  learning_rate: 1e-3
  eval_interval: 10

simpleP:
  base_model:
    dmodel: 32
    dff: 128

infrastructure:
  metric_logger:
    type: stdout
    name: simpleP_tiny_local
    tags:
      - nano
      - local
      - simpleP
