
infrastructure:
  server: entropy
  slurm:
    cpus-per-task: 16
    gres: gpu:8
    job-name: test
    mem_per_gpu: 120G
    nodes: 1
    partition: h100
    time: "2-00:00:00"

  venv_path: ???
  experiment_prepare_venv_path: ${infrastructure.venv_path}
  cemetery_experiments_dir: ~/llmrandom_cemetery

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git

switch:
  trainer:
    train_dataloader:
      dataset_path_c4: "/storage_nvme_1/llm-random/datasets/c4/train"
    eval_dataloader:
      dataset_path_c4: "/storage_nvme_1/llm-random/datasets/c4/validation"