
infrastructure:
  server: entropy
  slurm:
    cpus-per-task: 16
    gres: gpu:4
    job-name: test
    mem_per_gpu: 90G
    nodes: 1
    partition: h100
    time: "0-05:00:00"
    ntasks-per-node: 4

  venv_path: /dev/null # dev mas
  experiment_prepare_venv_path: ${infrastructure.venv_path}
  cemetery_experiments_dir: ~/llmrandom_cemetery

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
