
infrastructure:
  server: helios
  slurm:
    cpus-per-task: 12
    gres: gpu:4
    job-name: test
    mem_per_gpu: 90G
    nodes: 2
    partition: plgrid-gpu-gh200
    time: "2-00:00:00"

  venv_path: ???
  experiment_prepare_venv_path: ${infrastructure.venv_path}
  cemetery_experiments_dir: ~/llmrandom_cemetery

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git

switch:
  trainer:
    train_dataloader:
      dataset_path_c4: "/net/scratch/hscra/plgrid/plgmaciejpioro/c4/train" # helios
    eval_dataloader:
      dataset_path_c4: "/net/scratch/hscra/plgrid/plgmaciejpioro/c4/validation" # helios