
infrastructure:
  server: helios
  slurm:
    cpus-per-task: 16
    gres: gpu:4
    job-name: test
    mem_per_gpu: 90G
    nodes: 1
    partition: plgrid-gpu-gh200
    time: "0-05:00:00"
    ntasks-per-node: 4

  venv_path: $HOME/nano/.venv/bin/activate
  experiment_prepare_venv_path: ${infrastructure.venv_path}
  cemetery_experiments_dir: ~/llmrandom_cemetery

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
