_run_: true

infrastructure:
  server: local
  slurm: null

  cemetery_experiments_dir: null

cluster_switch:
  train_path_c4: "data"
  eval_path_c4: "data_eval"
  train_path_fineweb: "data"
  eval_path_fineweb: "data"
  train_path_sst2: "data/ft_dataset/sst2/train"
  eval_path_sst2: "data/ft_dataset/sst2/test"
  train_path_mnli: "data/ft_dataset/mnli/train"
  eval_path_mnli: "data/ft_dataset/mnli/validation"
  train_path_imdb: "data/ft_dataset/imdb/train"
  eval_path_imdb: "data/ft_dataset/imdb/test"
  
