_run_: true

infrastructure:
  server: local
  slurm: none

  venv_path: none
  experiment_prepare_venv_path: none
  cemetery_experiments_dir: none

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git