_run_: true

infrastructure:
  server: local
  slurm: null

  cemetery_experiments_dir: null

cluster_switch:
  train_path_c4: "data"
  eval_path_c4: "data_eval"
  train_path_fineweb: "data"
  eval_path_fineweb: "data"
  num_workers: 0
