defaults:
  - ../_cluster@_here_: helios
  - ../_model/llama@_here_: projected_mem_eff_8B
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default

init_model_opt_sched_fn:
  _partial_: true
  _target_: src.projected_compression.convert_memeff_to_hf.convert_pc_to_hf


common:
  sequence_length: 2048
  batch_size: 512

  dmodel: 1056 # 10p
  dff: 3168
  # dmodel: 2160 # 30p
  # dff: 6480
  # dmodel: 3072 # 50p
  # dff: 9216

trainer:
  _target_: src.projected_compression.trainer.PCTrainer
  gradient_accumulation_steps: 32 # not used
  n_steps: 0
  only_compress_model_gradient_clipping: true

  learning_rate: 20 # not used

  scheduler:
    warmup_steps: 40

  distributed:
    fsdp2: null

  checkpoint:
    load:
      path: ???

    save:
      path: ???
   
projected_compression:
  modules_to_shard:
    - src.projected_compression.mem_eff.CompressibleBlock
    - ${model.source_model.embedding._target_}
    - ${model.source_model.encoder.block_fn._target_}
    - ${model.source_model.head._target_}


  source_model_path: ??? # special PC_memeff checkpoint from llama_1B_conversion config experiment
  path_to_importances: ???

  init_norms_with_ones: false
  separate_block_optimizers: true
  adjust_grad_norm: false

  original_llama_path: "meta-llama/Llama-3.1-8B"

model:
  cast_bfloat16: false # whether to cast bfloat16 when calculating compressed matrix

infrastructure:
  metric_logger:
    name: PC_to_HF
    tags: 
      - nano
      - pc
      - llama_8
      - MEM_EFF_PC_to_HF

  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4 # helios
    # gres: "gpu:hopper:4" #lem
    time: "0-01:00:00"