defaults:
  - ../_cluster@_here_: entropy
  - ../_model@_here_: llama_3_1
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 1024
  batch_size: 512


trainer:
  gradient_accumulation_steps: 8
  ^n_steps: 
    # - 2048 # 1B tokens
    # - 4096
    # - 6144
    # - 8192
    # - 12288
    # - 16384
    - 20480
    # - 40960
    # - 61440

  learning_rate: 15

  train_dataloader:
    seed: 1000
  
  checkpoint:
   load:
    type: huggingface
    path: "meta-llama/Llama-3.2-1B"
   save:
    type: nano
    path: ??? # CHANGE


infrastructure:
  metric_logger:
    name: Llame_TA
    tags:
      - nano
      - pc
      - llama_1
      - FT

  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    time: "2-00:00:00"