defaults:
  # - ../_cluster@_here_: helios
  - ../_cluster@_here_: entropy
  - ../_model@_here_: llama_3_1
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: c4 # not used - loads slower
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common: 
  batch_size: 512

  dmodel: 1344 # 50
  dff: 5376
  # dmodel: 960 # 30
  # dff: 3840
  # dmodel: 448 # 10
  # dff: 1728


trainer:
  n_steps: 0 # not used
  learning_rate: 1 # not used
  gradient_accumulation_steps: 1 # not used

  checkpoint:
   load:
    # type: finalized_pc
    type: nano
    path: /storage_nvme_3/mstefaniak/nano_checkpoints/tmp/85234/2/step_12287
   save:
    type: huggingface
    path: /storage_nvme_3/mstefaniak/nano_checkpoints/tmp/85234/2/hf

# # 50p
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852568/0/step_2047
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852577/1/step_4095
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852598/2/step_8191
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852568/0/11884957/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_1BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852577/1/11884969/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_2BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852598/2/11884972/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_4BT/
#   rsync -avP asd/asd/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_6BT/

# # 30p
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852773/0/step_2047
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852780/1/step_4095
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852811/2/step_8191
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847874/3/step_12287
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852773/0/11884975/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_1BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852780/1/11884976/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_2BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852811/2/11884980/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_4BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847874/3/11884985/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_6BT/

# # 10p
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852818/0/step_2047
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852819/1/step_4095
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852826/2/step_8191
# # # /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847876/3/step_12287
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852818/0/11884986/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_1BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852819/1/11884990/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_2BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852826/2/11884994/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_4BT/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847876/3/11885001/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_6BT/

# # Define sources and destinations exactly as you provided
# sources=(
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852568/0/11884957/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852577/1/11884969/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852598/2/11884972/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852773/0/11884975/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852780/1/11884976/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852811/2/11884980/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847874/3/11884985/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852818/0/11884986/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852819/1/11884990/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852826/2/11884994/0/"
#     "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847876/3/11885001/0/"
# )

# dests=(
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_1BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_2BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_4BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_1BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_2BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_4BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_30p_6BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_1BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_2BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_4BT/"
#     "/net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_10p_6BT/"
# )

# for i in "${!sources[@]}"; do
#     src="${sources[$i]}"
#     dest="${dests[$i]}"
    
#     echo "----------------------------------------------------"
#     echo "Running Transfer $((i+1)) of 11"
#     echo "Dest: $dest"
    
#     mkdir -p "$dest"
#     rsync -avP "$src" "$dest"
# done

# echo "All transfers completed, Boss."





#   cp -r /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11847876/3/[id]/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_1B/
#   rsync -avP /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem/11852568/0/11884957/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_1B/
#   rsync -avP asd/asd/0/* /net/storage/pr3/plgrid/plggllmeffi/projected_compression/hf_checkpoints_1B/HPD_50p_1B/


infrastructure:
  metric_logger:
    name: conversion
    tags:
      - nano
      - pc
      - llama_1
      - hf_conversion
      # - TA10B
      # - randominit
      # - projected_compression
      - hard_pruning
      # - 10p
      # - 30p
      - 50p

  slurm: 
    gres: gpu:4
    time: "0-01:00:00"