defaults:
  - ../_cluster@_here_: entropy
  - ../_model@_here_: llama_3_1
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 1024
  batch_size: 512

  # target_dmodel: 448 # 10
  # target_dff: 1728
  target_dmodel: 960 # 30
  target_dff: 3840
  # target_dmodel: 1344 #50
  # target_dff: 5376
  # target_dmodel: 1728 # 75
  # target_dff: 6912


trainer:
  gradient_accumulation_steps: 8
  # gradient_accumulation_steps: 4
  ^n_steps: 
    - 2048 # 1B tokens
    # - 4096
    # - 6144
    # - 8192
    # - 12288
    # - 16384

  # learning_rate: 11 #optimal fo 10%
  learning_rate: 12 #optimal fo 30%
  # learning_rate: 12 #optimal fo 50%
  # learning_rate: 13 #optimal fo 75%
  # learning_rate: 12 #optimal fo randomi 50%

  scheduler:
    warmup_steps: 40

  checkpoint:
   load:
    type: huggingface
    path: "meta-llama/Llama-3.2-1B" 
   save:  
    type: nano
    path: ??? # CHANGE


infrastructure:
  metric_logger:
    name: Llame_HP
    tags:
      - nano
      - pc
      - llama_1
      - hard_pruning
      # - ta10b
      # - 10p
      - 30p
      # - 50p
      # - randomi
      # - magnitude
  
  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4 #dev
    time: "0-12:00:00"
 

apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    dimensions_importances_path: ??? # CHANGE
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}