defaults:
  # - ../_cluster@_here_: entropy
  # - ../_cluster@_here_: helios
  - ../_cluster@_here_: lem
  - ../_model@_here_: llama_3_8
  - ../_trainer@_here_: llama3_8B_distillation
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 2048
  batch_size: 512

  # target_dmodel: 1056 # 10p
  # target_dff: 3168
  # target_dmodel: 2160 # 30p
  # target_dff: 6480
  target_dmodel: 3072 # 50p
  target_dff: 9216
  
trainer:
  gradient_accumulation_steps: 32 # 50p # 30p # 10p 2x nodes
  # gradient_accumulation_steps: 128 # 1x node
  ^n_steps: 
    # - 6144
    # - 4096
    # - 2048
    - 1024
    # - 100

  learning_rate: 13 #optimal fo 50p
  # learning_rate: 13 #optimal fo 30p
  # learning_rate: 9 #optimal fo 10p # optimal lrs may vary in longer trainings

  scheduler:
    warmup_steps: 40

  eval_interval: 0
  eval_dataloader: None

  checkpoint:
   load:
    type: huggingface
    path: "meta-llama/Llama-3.1-8B" 
   save:  
    type: huggingface
    path: /lustre/pd03/plgrid/plgllmefficont3/mstefaniak/checkpoints/results # lem new
    # path: /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/test # helios   
    # path: /storage_nvme_3/mstefaniak/nano_checkpoints/tmp # entropy 

infrastructure:
  metric_logger:
    name: llama_hp_prune_distil
    tags:
      - nano
      - pc
      - llama_8
      - hard_pruning
      - distillation
      # - 10p
      # - 30p
      - 50p
  
  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: "gpu:hopper:4"
    # gres: gpu:4
    nodes: 2 #dev
    # time: "0-10:00:00" # 10p
    # time: "0-12:00:00" # 30p
    # time: "0-14:00:00" # 50p
    time: "2-00:00:00" # max
 
apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    # dimensions_importances_path: /storage_nvme_3/mstefaniak/pc/llama8_fw_importances_8m/117045/0/minitron_dimensions_importances.pt # entropy
    dimensions_importances_path: "/lustre/pd01/plgrid/plgllmefficont2/projected_compression/importances/8b/minitron_dimensions_importances.pt" # lem
    # dimensions_importances_path: /net/storage/pr3/plgrid/plggllmeffi/projected_compression/20260120_importances/minitron_dimensions_importances.pt # helios
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}
