defaults:
  - ../_cluster@_here_: entropy
  - ../_model/llmrandom@_here_: def_300
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: c4
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 512
  batch_size: 512
  batch_size: 16


trainer:
  gradient_accumulation_steps: 1
  ^n_steps: 
    - 4001 # 1B
    # - 8001
    # - 16001
    # - 24001

  learning_rate: 10

  scheduler:
    warmup_steps: 80
  
  checkpoint:
   load:
    type: llm-random
    path:   # - _cluster@_here_: helios

   save:
    type: nano
    path: ??? # CHANGE

  distributed: null

  train_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.gpt2_tokenize_fn

  eval_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.gpt2_tokenize_fn


infrastructure:
  metric_logger:
    name: LLMR_300_training
    tags:
      - nano
      - pc
      - llmr_300
      - test

  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:1
    time: "0-2:00:00"