defaults:
  - ../_cluster@_here_: entropy
  - ../_model/llmrandom@_here_: def_300
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: c4
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 512
  batch_size: 512

  # batch_size: 32
  # target_dmodel: 640 # 50
  # target_dff: 2560
  # target_dmodel: 480 # 35
  # target_dff: 1920
  target_dmodel: 320 # 20
  target_dff: 1280

trainer:
  gradient_accumulation_steps: 2
  ^n_steps: 
    - 4001 # 1B tokens
    # - 8001
    # - 16001
    # - 24001

  # learning_rate: 12 # 50 1B
  # learning_rate: 11 # 35 1B
  learning_rate: 11 # 20 1B
 
  scheduler:
    warmup_steps: 80

  checkpoint:
   load:
    type: llm-random
    path: ??? # CHANGE
   save:
    type: nano
    path: ??? # CHANGE

  train_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.gpt2_tokenize_fn

  eval_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.gpt2_tokenize_fn


infrastructure:
  metric_logger:
    name: LLMR_300_HP
    tags:
      - nano
      - pc
      - llmr_300
      - hard_pruning
      # - 65p
      # - 35p
      - 20p

  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    time: "0-8:00:00"


apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    dimensions_importances_path: ??? # CHANGE
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}