defaults:
  - ../_cluster@_here_: lem
  - ../_model/qwen@_here_: 1.7B
  - ../_trainer@_here_: qwen
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 1024
  batch_size: 512

  # base: dmodel 2048, dff 6144
  target_dmodel: 1344 # 50
  target_dff: 4032
  # target_dmodel: 960 # 30
  # target_dff: 2880
  # target_dmodel: 448 # 10
  # target_dff: 1344


trainer:
  gradient_accumulation_steps: 8
  ^n_steps:
    - 10 # 1B tokens
    # - 2048 # 1B tokens

  learning_rate: 12
  # ^learning_rate: [11, 12, 13, 14]

  scheduler:
    warmup_steps: 40

  original_llama_path: Qwen/Qwen3-1.7B-Base # reference HF model for the qwen exporter

  checkpoint:
    load:
      type: huggingface_qwen
      path: "Qwen/Qwen3-1.7B-Base"
    save:
      type: hf_only
      path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/checkpoints/hp/qwen/1_7B # CHANGE


infrastructure:
  metric_logger:
    name: Queen_HP
    tags:
      - nano
      - pc
      - qwen
      - 1.7B
      - hard_pruning
      - fineweb
      - 50p

  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:hopper:4
    time: "2-00:00:00"


apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    dimensions_importances_path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/importances/qwen/1_7B/5403539/0/minitron_dimensions_importances.pt # CHANGE
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}
