defaults:
  - ../_cluster@_here_: entropy
  - ../_model/smollm@_here_: def_1700
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 1024
  batch_size: 512


trainer:
  gradient_accumulation_steps: 1
  ^n_steps: 
    - 2048 # 1B tokens
    # - 4096
    # - 6144
    # - 8192
    # - 12288
    # - 16384

  learning_rate: 16

  scheduler:
    warmup_steps: 40

  checkpoint:
   load:
    type: huggingface
    path: "HuggingFaceTB/SmolLM-1.7B"
   save:
    type: nano
    path: ??? # CHANGE

  train_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.smollm_1700_tokenize_fn

  eval_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.smollm_1700_tokenize_fn


infrastructure:
  metric_logger:
    name: SMOLLM_training
    tags:
      - nano
      - pc
      - smollm_1700

  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    time: "0-12:00:00"

