trainer:
  _partial_: true
  _target_: src.core.trainer.Trainer
  eval_interval: ???
  n_eval_steps: ???
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  n_steps: ???
  learning_rate: ???
  weight_decay: 0.1
  final_downstream_eval: false
  fixed_eval: false

  scheduler:
    _partial_: true
    _target_: src.core.schedulers.WSDScheduler
    n_steps: ${trainer.n_steps}
    warmup_steps: ???
    decay_steps: 0

  distributed:
    fsdp2:
      modules_to_shard: 
        - ${model.embedding._target_}
        - ${model.encoder.block_fn._target_}
        - ${model.head._target_}