# @package _global_
defaults:
  - /_cluster@_here_: lem
  - /_model/context_scaling@_here_: k16 # k12, k16, k20
  - /_trainer@_here_: context_scaling
  - /_dataset@_here_: ctx_scl_dataset
  - /_checkpoints/context_scaling@_here_: shared_lem
  - /_misc@_here_: default
  - /_eval@_here_: joint
  - _self_

common:
  # MQA
  kv_heads: 1

  sequence_length: 2048
  batch_size: 64
  data_seed: 123
  model_seed: 123

trainer:
  gradient_accumulation_steps: 1
  n_steps: 320_001
  # n_steps: 190_001
  # n_steps: 100_001
  learning_rate: 12
  eval_interval: 100
  lm_eval_interval: 32_000
  # lm_eval_interval: 19_000
  # lm_eval_interval: 10_000

  train_dataloader:
    num_workers: 2
    dataset:
      data_generator:
        path: ${cluster_switch.train_path_fineweb}

  eval_dataloader:
    num_workers: 2
    dataset:
      data_generator:
        path: ${cluster_switch.eval_path_fineweb}

infrastructure:
  metric_logger:
    heavy_metrics_calculation_interval: 5_000
    name: scaling_dwnstrm
    tags:
      - nano
      - context_scaling
      - 42B
      - MHA
      - downstream_correlation
      - 1903_grid

  slurm:
    time: "2-00:00:00"
    gres: gpu:hopper:4
    job-name: ${infrastructure.metric_logger.name}