# @package _global_
defaults:
  - /_cluster@_here_:                lem
  - /_model/context_scaling@_here_:  template
  - /_trainer@_here_:                context_scaling
  - /_dataset@_here_:                fineweb
  - /_checkpoints/context_scaling@_here_: lem_1
  - /_infrastructure@_here_:         default
  - /_downstream_eval@_here_:        joint

  - /_feedforward:                   moe
  - /_attention:                     mha
  - /_parameterization:              simpleP_k12
  - _self_

common:
  n_blocks: 12
  ^batch_size: [8, 16, 32, 64]
  sequence_length: 1024

trainer:
  gradient_accumulation_steps: 1
  n_steps: 16_000
  ^learning_rate: [4, 6, 8, 10, 11, 12]
  eval_interval: 500
  fixed_eval: true

infrastructure:
  metric_logger:
    name: main_grid_1
    tags:
      - nano
      - main_grid_1
      - moe
      - mha
      - simpleP_k12
      - k12
      - bs${common.batch_size}
      - lr${trainer.learning_rate}
      - ${now:%Y-%m-%d}

  slurm:
    time: "0-04:00:00"
    gres: gpu:hopper:4
    job-name: ${infrastructure.metric_logger.name}
