
infrastructure:
  metric_logger:
    heavy_metrics_calculation_interval: 100
    new_wandb_job: true
    name: default
    type: wandb
    wandb_entity: ideas_cv
    project_name: llm-random-test
    tags:
      - new_wandb_job

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git

  generated_configs_path: generated_configs

  cemetery_experiments_dir: "~/llmrandom_cemetery"

evaluator: null