defaults:
  - base_pc_mem_eff
  - _self_

common:
  dmodel: 1024 # ~50% parameter compression
  dff: 3072 # ~50% parameter compression
  dhead: 128
  sequence_length: 512
  base_dmodel: 2048
  base_dff: 6144
  n_blocks: 28
  q_heads: 16
  kv_heads: 8
