# working 22.08

defaults:
  - _cluster@_here_: entropy_4
  - _model@_here_: llama_3_1
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  - _checkpoints@_here_: mas/hf_llama_3_1.yaml
  - _misc@_here_: default
  - _mas@_here_: default

common: 
  batch_size: 512

trainer:
  n_steps: 1001
  # n_steps: 0
  learning_rate: 3.0517578125e-05
  gradient_accumulation_steps: 8

  checkpoint:
   save:
    path: null
    # path: /storage_nvme_3/mstefaniak/nano_checkpoints/llaama3_1_nano

  train_dataloader:
    num_workers: 12
    seed: 20001
    total_batch_size: ${common.batch_size}

  eval_dataloader:
    num_workers: 12
    seed: 20001
    total_batch_size: ${common.batch_size}

infrastructure:
  metric_logger:
    name: test
    tags:
      - pc
      - nano
      - ft_llama3_1

