# work in progress

defaults:
  - _cluster@_here_: entropy
  - _model@_here_: llama_3_1
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  - _checkpoints@_here_: mas/hf_llama_3_1.yaml
  - _misc@_here_: default

common: 
  batch_size: 512

trainer:
  n_steps: 0
  learning_rate: 0.0000610352
  gradient_accumulation_steps: 1

  checkpoint:
   load:
    type: nano
    path: null # change
   save:
    type: huggingface
    path: null # change
  
infrastructure:
  metric_logger:
    name: test
    tags:
      - pc
      - nano
      - ft_llama3_1
      - hf_conversion

  slurm: 
    gres: gpu:4

