# work in progress

defaults:
  - _cluster@_here_: entropy_4
  - _model@_here_: llama_3_1
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  - _checkpoints@_here_: mas/hf_llama_3_1.yaml
  - _misc@_here_: default
  - _mas@_here_: default

trainer:
  n_steps: 0

  checkpoint:
   save:
    path: /storage_nvme_3/mstefaniak/nano_checkpoints/llama3_1_hf_test
   load:
    path: /storage_nvme_3/mstefaniak/nano_checkpoints/llama3_1_nano/63560/0/step_-1
  
infrastructure:
  metric_logger:
    name: test
    tags:
      - pc
      - nano
      - ft_llama3_1

