defaults:
  - _cluster@_here_: entropy
  - _model/llama@_here_: small_moe
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  - _checkpoints@_here_: none
  - _misc@_here_: default
  - _eval@_here_: basic
  - _self_

common:
  sequence_length: 1024
  batch_size: 64

model:
  embedding:
    vocab_size: 50257

trainer:
  gradient_accumulation_steps: 1
  n_steps: 1000
  learning_rate: 5e-4

  train_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.core.datasets.gpt2_tokenize_fn

  eval_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.core.datasets.gpt2_tokenize_fn

infrastructure:
  max_concurrent_jobs: 1

  metric_logger:
    type: wandb
    wandb_entity: ideas_cv
    project_name: llm-random-test
    name: moe_2gpu
    tags:
      - nano
      - remote
      - small
      - moe

  slurm:
    time: "0-02:00:00"
    gres: gpu:2
    job-name: ${infrastructure.metric_logger.name}

evaluator: null
