defaults:
  - _cluster@_here_: entropy
  - _model@_here_: tiny
  - _trainer@_here_: context_scaling
  - _dataset@_here_: c4
  - _checkpoints@_here_: none
  - _misc@_here_: default
  - _eval@_here_: incontext

common:
  tokenizer: gpt2
  sequence_length: 2048
  batch_size: 32

trainer:
  gradient_accumulation_steps: 1
  n_steps: 101
  learning_rate: 1e-3
  lm_eval_interval: 100  # 0 = disabled; set to N to run lm_eval every N steps during training

  train_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.core.datasets.gpt2_tokenize_fn
      

  eval_dataloader:
    dataset:
      tokenize_fn:
        _target_: src.core.datasets.gpt2_tokenize_fn

infrastructure:
  max_concurrent_jobs: 1

  metric_logger:
    # type: stdout
    name: tiny_remote
    tags:
      - nano
      - remote
      - tiny

  slurm:
    time: "00:10:00"
    gres: gpu:2
    job-name: ${infrastructure.metric_logger.name}

evaluator:
  limit: 16