defaults:
  - _cluster@_here_: local
  - _model@_here_: tiny
  - _trainer@_here_: context_scaling
  - _dataset@_here_: c4
  - _checkpoints@_here_: none
  - _infrastructure@_here_: default
  # - _downstream_eval@_here_: basic

common:
  sequence_length: 16
  batch_size: 2
  data_seed: 123

trainer:
  gradient_accumulation_steps: 1
  n_steps: 101
  learning_rate: 1e-3
  eval_interval: 5
  n_eval_steps: 2
  downstream_eval_interval: 0
  fixed_eval: true
  scheduler:
    warmup_steps: 10
    decay_steps: 10

  checkpoint:
    save:
      type: nano
      path: null

infrastructure:
  metric_logger:
    heavy_metrics_calculation_interval: 100 # change on longer runs
    name: tiny_Local
    tags:
      - nano
      - local
      - tiny

downstream_evaluator: null
