defaults:
  - base_pc_model
  - _self_

common:
  _target_: src.definitions.Common
  dmodel: 2048
  dff: 1024
  sequence_length: 512
  base_dmodel: 2048
  base_dff: 8192
  n_blocks: 16
  q_heads: 32
  kv_heads: 8