defaults:
  - base_pc_model
  - _self_

common:
  _target_: src.definitions.Common
  dmodel: 64
  dff: 256
  dhead: 32
  sequence_length: 1024
  base_dmodel: 128
  base_dff: 512
  n_blocks: 2
  q_heads: 4
  kv_heads: 2

