defaults:
  - base_pc_model
  - _self_

common:
  _target_: src.definitions.Common
  dmodel: 2816
  dff: 9856
  dhead: 128
  sequence_length: 1024
  base_dmodel: 4096
  base_dff: 14336
  n_blocks: 32
  q_heads: 32
  kv_heads: 8
