defaults:
  - base_model
  - _self_

common:
  dmodel: 768
  dff: 2048
  dhead: 64
  n_blocks: 12
  q_heads: 32
  kv_heads: 32

model:
  encoder:
    block_fn:
      ff_layer_fn:
        _target_: src.core.moe.MoE
        _partial_: true
        dmodel: ${common.dmodel}
        dff: ${common.dff}
        num_experts: 16
        num_experts_per_tok: 1
        capacity_factor: 1.25
        moe_load_balancing_loss_factor: 0.01
        activation_function: swiglu
        init_scale: 0.02
