# @package _global_
defaults:
  - ../_cluster@_here_: entropy
  - ../_model/context_scaling@_here_: k8
  - ../_trainer@_here_: context_scaling
  - ../_dataset@_here_: ctx_scl_dataset
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default
  - _self_

common:
  sequence_length: 1024
  batch_size: 64

trainer:
  gradient_accumulation_steps: 1
  n_steps: 16_000
  ^learning_rate: [4, 5, 6, 7, 8, 9, 10, 11]
  eval_interval: 500

simpleP:
  base_dmodel: 256

infrastructure:
  metric_logger:
    name: simpleP_dense_k8
    tags:
      - nano
      - simpleP_dense3
      - k8

  slurm:
    time: "0-04:00:00"
    gres: gpu:1
    job-name: ${infrastructure.metric_logger.name}
