# Basic evaluation configuration
evaluator:
  _partial_: true
  _target_: src.core.eval.Evaluator
  tokenizer: ${common.tokenizer}
  tasks:
    - wikitext
    - piqa
  limit: null  # No limit, evaluate on full datasets
  max_length: ${common.sequence_length}
  max_gen_toks: 256
  batch_size: 1
