
infrastructure:
  # venv_path: /net/scratch/hscra/plgrid/plgcrewtool/siemaeniu/bin/activate
  venv_path: /net/scratch/hscra/plgrid/plgmstefaniak/envs/nano2/nano/bin/activate  
  experiment_prepare_venv_path: /net/scratch/hscra/plgrid/plgmstefaniak/envs/nano/.venv_local/bin/activate
  # slurm:
  #   export: ALL,HF_HUB_CACHE="/net/scratch/hscra/plgrid/plgmstefaniak/hf_cash"
  modules_to_add:
    - ML-bundle/25.04
  #   - CUDA/12.8.0
    # - ML-bundle/24.06a
    # - ML-bundle/25.04
    # - pytorch3d/0.7.8

# ${CUDA_VISIBLE_DEVICES}

# /net/scratch/hscra/plgrid/plgmstefaniak/hf_cash/my_models/Llama-3.1-8B